### ISSUE TITLE
Pylint

### ISSUE THREAD

**Issue by tungufoss** [HI-IDN/IDeLM-APAP-learning-fairness-models#14]
Integrating Pylint into your GitHub repository to automatically check your Python code for errors and enforce coding standards is a great way to maintain high code quality. Here's a step-by-step guide on how you can set up Pylint with GitHub Actions, which is a feature in GitHub allowing you to automate workflows directly in your GitHub repository:

- [x] Step 1: Set Up Pylint in Your Local Environment

Before integrating Pylint into GitHub, ensure it's working in your local development environment.

Install Pylint: If you haven't already, install Pylint using pip:

``` bash 
pip install pylint
```
Run Pylint Locally: You can run Pylint on your project to see the initial linting reports. Navigate to your project directory and run:

``` bash 
pylint your_project_directory
```

- [ ] Step 2: Create a GitHub Actions Workflow

Navigate to Your Repository: Go to your GitHub repository where you want to add Pylint.

Create a Workflow File: In your repository, navigate to the Actions tab, click "New workflow", and then set up a workflow yourself. This will open an editor in GitHub where you can define your workflow. Alternatively, you can create a file manually under .github/workflows/ directory in your repository. You might name it python-lint.yml.

Define the Workflow for Pylint: In the workflow file, define the steps that GitHub Actions will follow to check out your code and run Pylint. Here is an example workflow definition:

``` yaml
name: Python Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify the Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Run Pylint
      run: |
        pylint your_project_directory

```

- [ ] Step 3: Commit and Push Your Workflow File

After defining the workflow, commit the .github/workflows/python-lint.yml file to your repository. GitHub Actions will automatically recognize this file and start running the workflow based on the triggers defined (on: [push, pull_request] in this case).

- [ ] Step 4: Monitor the Workflow

View Workflow Results: After pushing your workflow file, you can see the Actions tab in your GitHub repository for the results of the workflow runs. If Pylint finds issues, the workflow will fail, and you can see the details by clicking on the specific run.

Adjust Pylint Settings: If necessary, you can adjust Pylint's behavior by adding a .pylintrc file to your repository's root. This file allows you to configure Pylint rules, disable specific warnings, or customize the linting process.

By following these steps, you'll have Pylint automatically checking your Python code for style and errors every time you push changes or create a pull request, helping to maintain a consistent code quality standard in your project.
